version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

  jobs:
    test:
      docker:
        - image: circleci/ruby:2.6.1
      working_directory: ~/repo
      steps:
        - checkout

  
  
  workflows:
    version: 2
    workflows:
      jobs:
